all:
  children:
    ci_servers:
      hosts:
        localhost:
          ansible_connection: local
        jenkins:
          ansible_host: 192.168.106.131
          ansible_user: user1
          ansible_ssh_private_key_file: /home/user1/Unda/.data/ssh-keys/id_unda
      vars:
        ansible_user: '{{ lookup(''env'', ''ANSIBLE_USER'') | default(''root'', true)
          }}'
